name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assemble
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.VRPACKAGETOKEN }}
    - name: Test with Gradle
      run: ./gradlew -Djava.awt.headless=true check 
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.VRPACKAGETOKEN }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
